export const GET_SUBJECT_LIST = 'GET_SUBJECT_LIST'
export const GET_SECSUBJECT_LIST = 'GET_SECSUBJECT_LIST'
export const GET_UPDATESUBJECT_LIST = 'GET_UPDATESUBJECT_LIST'
export const DELSUBJECT_LIST = 'DELSUBJECT_LIST'
